language: cpp

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1

compiler:
  - gcc
  - clang

cache:
  directories:
    - $HOME/deps
before_install:
  # set up dependency cache
  - if [ ! -d $HOME/deps ]; then mkdir $HOME/deps; fi
  - if [ ! -f $HOME/deps/tetgen1.4.3.tar.gz ]; then wget --quiet --directory-prefix=$HOME/deps http://tetgen.org/files/tetgen1.4.3.tar.gz; fi
  - if [ ! -f $HOME/deps/tetgen_cmake.tgz ]; then wget --quiet --directory-prefix=$HOME/deps http://www.sci.utah.edu/devbuilds/seg3d/tetgen_cmake.tgz; fi
  - if [ ! -f $HOME/deps/release-1.7.0.tar.gz ]; then wget --quiet --directory-prefix=$HOME/deps https://github.com/google/googletest/archive/release-1.7.0.tar.gz; fi
  - if [ ! -f $HOME/deps/3.2.10.tar.gz ]; then wget --quiet --directory-prefix=$HOME/deps http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz; fi
  - pip install --user cpp-coveralls
  - ls $HOME/deps
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
script:
  # build Tetgen dependency
  - mkdir build
  - cd build
  - tar xzf $HOME/deps/tetgen1.4.3.tar.gz
  - pushd tetgen1.4.3
  - make tetlib
  - tar xzf $HOME/deps/tetgen_cmake.tgz
  - popd
  # build Googletest dependency
  - tar xzf $HOME/deps/release-1.7.0.tar.gz
  - pushd googletest-release-1.7.0
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - popd
  # untar Eigen dependency (no build needed)
  - tar xzf $HOME/deps/3.2.10.tar.gz
  # build ImplicitFunction library
  - cmake -DBUILD_TESTING:BOOL=ON -DENABLE_COVERAGE:BOOL=ON -DTravisCI_BUILD:BOOL=ON
          -DGTEST_INCLUDE_DIR:PATH=`pwd`/googletest-release-1.7.0/include
          -DGTEST_LIBRARY:FILEPATH=`pwd`/googletest-release-1.7.0/build/libgtest.a
          -DGTEST_MAIN_LIBRARY:FILEPATH=`pwd`/googletest-release-1.7.0/build/libgtest_main.a
          -DTetgen_DIR:PATH=`pwd`/tetgen1.4.3
          -DEIGEN3_INSTALL_DIR:PATH=`pwd`/eigen-eigen-b9cd8366d4e8 ..
  - make -j4
  - ./ImplicitFunction_Tests

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls --exclude build --exclude Tests --gcov-options '\-lp'
