name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: mkdir bin
    - name: configure
      run: cd bin && cmake ..
    - name: make
      run: make
    - name: make test
      run: make test
